name: Release
on:
  workflow_dispatch:
  push: 
    branches:
      - main
  pull_request:
jobs:  
  docker_push:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        strimzi_kafka_version: 
          - "0.33.0-kafka-3.2.3"
          - "0.33.0-kafka-3.3.2"
          - "0.33.0-kafka-3.3.1"
          # - "0.33.0-kafka-3.2.1"
          # - "0.33.0-kafka-3.2.0"
          # - "0.32.0-kafka-3.2.1"
          # - "0.32.0-kafka-3.2.0"
          # - "0.32.0-kafka-3.2.3"
          # - "0.32.0-kafka-3.3.1"
          # - "0.31.0-kafka-3.1.0"
          # - "0.31.0-kafka-3.1.1"
          # - "0.31.0-kafka-3.2.1"
          # - "0.31.0-kafka-3.2.0"
        aws_msk_iam_auth_version:
          - "latest"
          - "1.1.6"
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            STRIMZI_KAFKA_VERSION=${{ matrix.strimzi_kafka_version }}
            AWS_MSK_IAM_AUTH_VERSION=${{ matrix.aws_msk_iam_auth_version }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/strimzi-kafka-operator-aws-msk-iam-auth:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/strimzi-kafka-operator-aws-msk-iam-auth:${{ matrix.strimzi_kafka_version }}-aws-${{ matrix.aws_msk_iam_auth_version }}